[workspace]
resolver = "2"

members = [
	"aime-net",
	"edit-rating-analyzer-js", "generate-config",
	"maimai-scraping",
	"maimai-scraping-utils",
	"maimai-watcher",
	"rating-target-viewer",
	"screenshot-generator",
]
