[package]
name = "maimai-scraping"
version = "0.1.0"
authors = ["TonalidadeHidrica <47710717+TonalidadeHidrica@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.9", features = ["cookies"] }
tokio = { version = "0.2.13", features = ["macros"] }
anyhow = "1.0.37"
scraper = "0.12.0"
once_cell = "1.5.2"
serde = "1.0.118"
serde_json = "1.0.61"
